name: Python Linters
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  pylint:
    runs-on: ubuntu-latest
    env:
      WANDB_MODE: offline
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/worker.txt
          pip install pylint

      - name: Install project package
        run: |
          pip install -e .
          pushd cloudsort/sortlib && python setup.py build_ext --inplace && popd

      - name: Run linter
        run: pylint cloudsort/**/*.py
